### ISSUE TITLE
和其他脚本发生冲突

### ISSUE THREAD

**Issue by wadawada** [maxzhang666/OneKeyVip#11]
同时使用这两个脚本会使bilibili播放器加戴失败
https://github.com/the1812/Bilibili-Evolved
https://github.com/the1812/Bilibili-Evolved/issues/503#issuecomment-624010135

**Comment by maxzhang666** [comment]
没有重现到这个问题，你使用的是什么版本

**Comment by maxzhang666** [comment]
调整网速后重现了，下个版本修复，变更按钮位置
