### ISSUE TITLE
4.2.29 版本 Microsoft Edge 版本 91.0.864.48 (官方内部版本) (64 位) 开启后淘宝滚不动,没有滚动条

### ISSUE THREAD

**Issue by longforus** [maxzhang666/OneKeyVip#16]
关闭脚本刷新正常

**Comment by maxzhang666** [comment]
具体哪个页面？

**Comment by longforus** [comment]
@maxzhang666 是详情页,但是今天我在公司一样的版本和浏览器,又没有问题了,可能是我屋里的网络或者电脑问题吧.

**Comment by maxzhang666** [comment]
> @maxzhang666 是详情页,但是今天我在公司一样的版本和浏览器,又没有问题了,可能是我屋里的网络或者电脑问题吧.

有时不同的页面匹配规则走的可能会不一样,问题再出现了把网页地址也带上 我排查下

**Comment by maxzhang666** [comment]
在edge测了一下确实有这个问题出现

新版本已修复该问题
