### ISSUE TITLE
脚本安装失败

### ISSUE THREAD

**Issue by VanDerYibiao** [maxzhang666/OneKeyVip#17]
点击安装脚本，chrome提示有风险。询问是否继续安装，点继续后无反应，只弹出一条invalid script header。
油猴版本4.13，测试其他脚本可以成功安装，唯独玩的嗨不行。

**Comment by maxzhang666** [comment]
从哪里安装的？

**Comment by VanDerYibiao** [comment]
> 从哪里安装的？
就这个project里，http://tools.wandhi.com/scripts

**Comment by maxzhang666** [comment]
> > 从哪里安装的？
> > 就这个project里，http://tools.wandhi.com/scripts

感谢反馈
这就去修
