### ISSUE TITLE
能不能加一个是否开启提醒更新的功能呀

### ISSUE THREAD

**Issue by Dnine7** [maxzhang666/OneKeyVip#26]
每次一更新在左下角就显示，次数少还行 更新太频繁了

**Comment by maxzhang666** [comment]
新版本支持了更新弹出的控制

**Comment by aqdd** [comment]
> 新版本支持了更新弹出的控制

在Tampermonkey中的脚本列表里显示的版本号是4.9.4，但是在Tampermonkey扩展图标里点“控制中心”，显示的当前版本是4.8.8，在Tampermonkey脚本设置里把检查更新也取消勾选了，左下角还是会弹。

**Comment by maxzhang666** [comment]
> > 新版本支持了更新弹出的控制
> 
> 
> 
> 在Tampermonkey中的脚本列表里显示的版本号是4.9.4，但是在Tampermonkey扩展图标里点“控制中心”，显示的当前版本是4.8.8，在Tampermonkey脚本设置里把检查更新也取消勾选了，左下角还是会弹。

你这个情况是安装了俩脚本的原因，你看看脚本管理器，把4.8.8删了就好了

**Comment by aqdd** [comment]
> 你这个情况是安装了俩脚本的原因，你看看脚本管理器，把4.8.8删了就好了

ok
