### ISSUE TITLE
这怎么解析视频都是色情广告

### ISSUE THREAD

**Issue by xiongkai** [maxzhang666/OneKeyVip#29]

**Comment by maxzhang666** [comment]
是哪个接口？我来删除它

接口里的任何广告都不要相信，我无法控制接口里的广告，但我可以删除接口

**Comment by xiongkai** [comment]
VIP解析 点击后 弹出的新窗口就是色情网站

**Comment by maxzhang666** [comment]
> VIP解析 点击后 弹出的新窗口就是色情网站，不是每天都这样

点的哪里弹新窗口？？我不记得有这种按钮
