### ISSUE TITLE
[新增功能] 语雀还不支持自动跳转

### ISSUE THREAD

**Issue by rwerplus** [maxzhang666/OneKeyVip#30]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）

语雀还不支持自动跳转

**Comment by maxzhang666** [comment]
有没有示例页面？我创建了个文档添加了超链接没发现中间页

**Comment by rwerplus** [comment]
先关闭，之前看到了一个跳转验证的页面，目前还没找到，找到了我发个链接
