### ISSUE TITLE
IDM的用户代理（UA）应该填什么

### ISSUE THREAD

**Issue by jafox-12** [maxzhang666/OneKeyVip#31]
IDM无法识别出文件类型，进而无法下载（见下图），怀疑是UA不匹配。之前因为其他插件的使用更改过UA
![image](https://github.com/maxzhang666/OneKeyVip/assets/74179218/7ed2909c-ffc3-418b-a3a0-fdee5cf59d6e)

**Comment by maxzhang666** [comment]
pan.baidu.com试试

**Comment by maxzhang666** [comment]
啊是quark啊

夸克不需要ua

**Comment by jafox-12** [comment]
明白了。在夸克，点“下载”然后转IDM，等久一会儿就可以下载；“复制链接“不太ok
![image](https://github.com/maxzhang666/OneKeyVip/assets/74179218/b526d38e-c4cb-4c59-a8f7-a91abd51f9c3)

**Comment by maxzhang666** [comment]
> 明白了。在夸克，点“下载”然后转IDM，等久一会儿就可以下载；“复制链接“不太ok ![image](https://private-user-images.githubusercontent.com/74179218/313521568-b526d38e-c4cb-4c59-a8f7-a91abd51f9c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjU1MDMsIm5iZiI6MTcxMDcyNTIwMywicGF0aCI6Ii83NDE3OTIxOC8zMTM1MjE1NjgtYjUyNmQzOGUtYzRjYi00YzU5LWE4ZjctYTkxYWJkNTFmOWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAxMjY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzVkYzBlODlkYWIwNzRmZjc4NDViMDkwMDM1ZjdlZTRmYzUxZGUxNmIwNGQ0ODMyZGQ3YjEwYmFmNzQ3OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gNgAp22gtjtW7KBkZQqCJn15AJfrjVimgwXfOpgFTJg)

是的，因为quark的下载会验证cookie

光复制链接没有cookie是没权限下载的

**Comment by jafox-12** [comment]
多谢了
