### ISSUE TITLE
能否为wy邮箱跳转也增加自动跳转的功能

### ISSUE THREAD

**Issue by rwerplus** [maxzhang666/OneKeyVip#32]
## 1. 准备工作（确认预先完成的操作）

- [x] 我确认使用的是当前脚本的最新版本。
- [x] 我已在Issues或Discussions中搜索过此需求，但没有找到类似的提案。

## 2. 请描述您所需要的新功能或新建议（清晰简明地描述您的需求是什么）
希望在邮箱跳转第三方页面没有这个提示

## 3. 附加信息或屏幕截图（此处添加可帮助表明您意图的附加信息或截图）
![image](https://github.com/maxzhang666/OneKeyVip/assets/48611415/2e3e806d-8ecd-4464-af7c-15b4acbe43aa)

**Comment by maxzhang666** [comment]
这是什么邮箱？

**Comment by rwerplus** [comment]
> 这是什么邮箱？

网易邮箱

**Comment by maxzhang666** [comment]
看了一下这个是弹窗的形式
暂时只支持中间页的自动跳转
登了一下网易说我账号有安全问题居然还让我自己发短信验证
辣鸡网易😛
