### ISSUE TITLE
[功能优化] 搜索时按钮能否靠下点，或者增加个位置记忆功能

### ISSUE THREAD

**Issue by zeroskylian** [maxzhang666/OneKeyVip#35]
![image](https://github.com/user-attachments/assets/040085a1-969d-4454-9e05-1c90c491c874)

如图所示，如果浏览器未最大化，会导致悬浮按钮被遮挡

**Comment by maxzhang666** [comment]
后续调整位置到左下角

**Comment by zeroskylian** [comment]
好的，多谢
