### ISSUE TITLE
安装不了，提示invalid script header.

### ISSUE THREAD

**Issue by booting2008** [maxzhang666/OneKeyVip#36]
大大看看是什么问题：
Edge: ![image](https://github.com/user-attachments/assets/e3e9976d-4aba-48d8-a53f-7945a38ceb63)
油猴：
![image](https://github.com/user-attachments/assets/6e0292a0-649d-4f12-8206-16ba4c40a8bb)
安装失败：
![image](https://github.com/user-attachments/assets/87430378-986b-417a-bbbb-96e98220272a)

**Comment by maxzhang666** [comment]
用脚本猫就可以了
